{{- if and .Values.ingress.enabled .Values.api.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-api
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /api
{{- end }}
