{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio.fullname" . }}-api
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "portfolio.api.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio.fullname" . }}-ui
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: {{ .Values.ui.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "portfolio.ui.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.chroma.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio.fullname" . }}-chroma
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
    app.kubernetes.io/component: chroma
spec:
  type: {{ .Values.chroma.service.type }}
  ports:
    - port: {{ .Values.chroma.service.port }}
      targetPort: {{ .Values.chroma.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "portfolio.chroma.selectorLabels" . | nindent 4 }}
{{- end }}
