apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-cloudflared
  namespace: portfolio
spec:
  podSelector: {}   # all pods in portfolio
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: cloudflared