---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "portfolio.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.service.ui.type }}
  ports:
    - port: {{ .Values.service.ui.port }}
      targetPort: {{ .Values.service.ui.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "portfolio.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
