apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: localstack
  labels:
    app: localstack
spec:
  type: NodePort
  ports:
  - port: 4566
    targetPort: 4566
    nodePort: 30566
    protocol: TCP
    name: edge
  selector:
    app: localstack
