{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio.fullname" . }}-api
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "portfolio.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: {{ .Values.api.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "portfolio.api.selectorLabels" . | nindent 4 }}
{{- end }}