{{- if .Values.chromadb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio.fullname" . }}-chromadb
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "portfolio.chromadb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.chromadb.service.type }}
  ports:
  - port: {{ .Values.chromadb.service.port }}
    targetPort: {{ .Values.chromadb.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "portfolio.chromadb.selectorLabels" . | nindent 4 }}
{{- end }}