{{- if .Values.ui.ingress.enabled -}}
{{- $fullName := include "portfolio.fullname" . -}}
{{- $uiSvcPort := .Values.ui.service.port -}}
{{- if and .Values.ui.ingress.className (not (hasKey .Values.ui.ingress.annotations "kubernetes.io/ingress.class")) }}
  {{- $_ := set .Values.ui.ingress.annotations "kubernetes.io/ingress.class" .Values.ui.ingress.className}}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
  {{- with .Values.ui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ui.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ui.ingress.className }}
  {{- end }}
  {{- if .Values.ui.ingress.tls }}
  tls:
    {{- range .Values.ui.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ui.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-ui
                port:
                  number: {{ $uiSvcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-ui
              servicePort: {{ $uiSvcPort }}
              {{- end }}
          {{- end }}
          # API routes
          - path: /api
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-api
                port:
                  number: {{ $.Values.api.service.port }}
              {{- else }}
              serviceName: {{ $fullName }}-api
              servicePort: {{ $.Values.api.service.port }}
              {{- end }}
          # Avatar creation routes
          - path: /avatar
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-avatar-creation
                port:
                  number: {{ $.Values.avatarCreation.service.port }}
              {{- else }}
              serviceName: {{ $fullName }}-avatar-creation
              servicePort: {{ $.Values.avatarCreation.service.port }}
              {{- end }}
          # RAG pipeline API routes
          - path: /rag
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-rag-pipeline
                port:
                  number: {{ (index $.Values.ragPipeline.service.ports 0).port }}
              {{- else }}
              serviceName: {{ $fullName }}-rag-pipeline
              servicePort: {{ (index $.Values.ragPipeline.service.ports 0).port }}
              {{- end }}
          # Jupyter Lab access
          - path: /jupyter
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-rag-pipeline
                port:
                  number: {{ (index $.Values.ragPipeline.service.ports 1).port }}
              {{- else }}
              serviceName: {{ $fullName }}-rag-pipeline
              servicePort: {{ (index $.Values.ragPipeline.service.ports 1).port }}
              {{- end }}
    {{- end }}
{{- end }}